### ISSUE TITLE
Run Error

### ISSUE THREAD

**Issue by Puie** [eric19960304/Kana-Listening-Test#2]
There is nothing show up after run the app on the simulator.
![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-15 at 00 13 06](https://user-images.githubusercontent.com/35200707/72365932-d1ba7280-372b-11ea-9102-fc4f194f28c6.png)

**Comment by eric19960304** [comment]
Seems like I messed up something during switching to use sqlite. Will try to fix it tonight, thank you for your issue.

**Comment by eric19960304** [comment]
Fixed with https://github.com/eric19960304/kana-listening/commit/ecb9b52f962aa39a11c27cef83db29c1e631675f
