### ISSUE TITLE
[VERBOSE-2:shell.cc(407)] Could not launch engine with configuration.

### ISSUE THREAD

**Issue by Puie** [eric19960304/Kana-Listening-Test#3]
Still got the white screen error and app is not working just showing white blank screen.

![Simulator Screen Shot - iPhone 11 Pro Max - 2020-01-16 at 22 12 17](https://user-images.githubusercontent.com/35200707/72536735-66001300-38ad-11ea-9520-485a94d6d10a.png)

**Comment by eric19960304** [comment]
Is it a real device or simulator?
Also it will be greate if you could provide the iOS version you are using.

**Comment by Puie** [comment]
I use the xcode simulator. Xcode version 11.3, simulator model is 11 Pro Max. iOS 13. Please fix this.

**Comment by eric19960304** [comment]
Changed some code, it work for me (have to wait for around 10 seconds for the simulator to load the app for the first run).
<img width="429" alt="Screenshot 2020-02-17 at 4 23 41 AM" src="https://user-images.githubusercontent.com/13762656/74611249-5fc7b580-513d-11ea-9bfd-c79cd2db3e22.png">
